Update ISSUE_TEMPLATES and PR TEMPLATE
secureCodeBox/secureCodeBox-v2-alpha pull request #124
Opened 2020-09-30 08:37 UTC by rseedorff

This PR updates the project specific ISSUE_TEMPLATES and PR TEMPLATE to improve the community process.

2020-09-30 10:42 UTC, fuhrmeistery requested changes

2020-09-30 10:42 UTC, fuhrmeistery commented on .github/ISSUE_TEMPLATE/new_security_scanner.md
> +- [ ] Add (optional) a Dockerfile for the scanner if there is now existing one public available on dockerHub
I think there are two typos:
Add (optional) a Dockerfile for the scanner if there is no existing one publicly available on dockerHub

2020-09-30 10:42 UTC, fuhrmeistery commented on .github/ISSUE_TEMPLATE/new_hook.md
> +- [ ] Add (optional) a Dockerfile for the scanner if there is now existing one public available on dockerHub
I think there are some typos:
Add (optional) a Dockerfile for the hook if there is no existing one publicly available on dockerHub

2020-09-30 10:42 UTC, fuhrmeistery commented on .github/ISSUE_TEMPLATE/new_hook.md
> +- [ ] Use the parserSDK to implement a new findings parser (currently based on NodeJS)
I'm not sure if this step is needed for a hook

2020-09-30 10:42 UTC, fuhrmeistery commented on .github/ISSUE_TEMPLATE/new_hook.md
> +- [ ] Add some example scan.yaml and finding.yaml files in the example folder
I'm not sure if this step is needed for a hook

2020-10-01 08:05 UTC, J12934 approved these changes

2020-10-01 08:05 UTC, merged