Add securityContexts to secureCodeBox Components
secureCodeBox/secureCodeBox-v2-alpha pull request #129
Opened 2020-10-02 16:02 UTC by J12934

Add configurable [Kubernetes securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) to all included pods.

For all direct "secureCodeBox" components (Operator, Lurcher, Parser & Hooks) these are completely pre-configured to enable all securityContext features which are generally available on all supported Kubernetes Versions.

For the scanner container these have not yet been configured, as this might required more tweaking to properly support the individual scanner without messing with their functionality. For now only Nmap has been configured with a proper securityContext. As the securityContext is exposed via the Helm values it can be configured individually by the user.

2020-10-02 16:05 UTC, J12934 commented
While adding the securityContext i've noticed that all scanners had `env`, `extraVolumes`, `extraVolumeMounts`, `extraContainers` config values in their Helm values but their templates didn't really support them. I've added them to all integrated scanners.

2020-10-05 09:41 UTC, fuhrmeistery requested changes

2020-10-05 09:41 UTC, fuhrmeistery commented on operator/README.md
> +| securityContext.allowPrivilegeEscalation | bool | `false` | Ensures that users privilidges canout be escalated |
Ensure that users privileges cannot be escalated

2020-10-05 09:41 UTC, fuhrmeistery commented on operator/README.md
> +| securityContext.capabilities.drop[0] | string | `"all"` | This drops all linux privilidges from the operator container. They are not required |
privileges

2020-10-05 09:41 UTC, fuhrmeistery commented on operator/README.md
> +| securityContext.privileged | bool | `false` | Ensures that the operator container is not run in privilidged mode |
privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +You can deployed the ScanType with the config like this:
You can deploy...

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +cat <<EOF | helm install nmap-privilidged ./scanners/nmap --values -
nmap-privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +  scanType: "nmap-privilidged"
nmap-priviledged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +| scannerJob.securityContext.allowPrivilegeEscalation | bool | `false` | Ensures that users privilidges canout be escalated |
privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +| scannerJob.securityContext.capabilities.drop[0] | string | `"all"` | This drops all linux privilidges from the container. |
privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md
> +| scannerJob.securityContext.privileged | bool | `false` | Ensures that the scanner container is not run in privilidged mode |
privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on hook-sdk/nodejs/Dockerfile
>  ENTRYPOINT ["node", "/home/app/hook-wrapper/hook-wrapper.js"]
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on operator/README.md
> -| image.pullPolicy | string | `"Always"` | Image pull policy |
Maybe revert to Always

2020-10-05 09:41 UTC, fuhrmeistery commented on operator/values.yaml
> -  pullPolicy: Always
Maybe switch back to Always

2020-10-05 09:41 UTC, fuhrmeistery commented on parser-sdk/nodejs/Dockerfile
>  ENTRYPOINT ["node", "/home/app/parser-wrapper/parser-wrapper.js"]
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md.gotmpl
> +You can deployed the ScanType with the config like this:
You can deploy [..]

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md.gotmpl
> +cat <<EOF | helm install nmap-privilidged ./scanners/nmap --values -
nmap-privileged

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/README.md.gotmpl
>  {{ template "chart.valuesTable" . }}
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/nmap/scanner/Dockerfile
>  CMD [nmap]
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/sslyze/templates/sslyze-scan-type.yaml
> +            {{- toYaml .Values.scannerJob.extraVolumes | nindent 12 }}
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/test-scan/templates/test-scan-scan-type.yaml
> +            {{- toYaml .Values.scannerJob.extraVolumes | nindent 12 }}
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/trivy/templates/trivy-scan-type.yaml
> +            {{- toYaml .Values.scannerJob.extraVolumes | nindent 12 }}
Newline at EOF missing

2020-10-05 09:41 UTC, fuhrmeistery commented on scanners/wpscan/templates/wpscan-scan-type.yaml
> +            {{- toYaml .Values.scannerJob.extraVolumes | nindent 12 }}
Newline at EOF missing

2020-10-05 13:58 UTC, fuhrmeistery approved these changes

2020-10-05 13:58 UTC, merged